### ISSUE TITLE
enjoying it so far

### ISSUE THREAD

**Issue by chadbr** [MrChuckomo/poddycast#17]
Keep it up - I like where it's going.

Need any help?

**Comment by MrChuckomo** [comment]
Thanks, I appreciate it.

If you have already something in mind just let me know. Then we can discuss this. 
First I have to figure out myself what comes next apart from the obvious things like:

- show notes support
- sleep timer
- import
- export
- bug fixes 
- etc. 

But feel free to explore the project and create PR with your ideas/improvements. 
I will keep you in mind. Maybe I have something for you in the future.
