### ISSUE TITLE
Episode list information

### ISSUE THREAD

**Issue by JosephSamela** [MrChuckomo/poddycast#30]
Click on a show to view episodes. See all that white space? 

How about sprucing these list elements with some more info. For example, description, publication date, time remaining, etc.

![screenshot from 2018-04-23 21-51-43](https://user-images.githubusercontent.com/16111451/39161821-8d244ae2-4740-11e8-998c-d328b5eb8fe3.png)

For reference here's the layout in Google Music.

![screenshot 2018-04-23 at 9 52 58 pm](https://user-images.githubusercontent.com/16111451/39161864-ba952960-4740-11e8-92ea-636b1f4f4d5f.png)

Maybe even options of sorting episodes? Sort by date for example.

**Comment by WeaverOfTheWeb** [comment]
@alexdevero @MrChuckomo The Podcasts own RSS feed contains episode descriptions/summaries so an alt API wouldn't be needed.

Within the saveLatestEpisode() of feed.js you could add an additional line during the data collation with something like this:

var EpisodeDescription = xmlDoc.getElementsByTagName('itunes:summary')[0] !== undefined ? xmlDoc.getElementsByTagName('itunes:summary')[0].textContent : xmlDoc.getElementsByTagName('description')[0].textContent
