### ISSUE TITLE
Feature: Add support for import of opml files

### ISSUE THREAD

**Issue by alexdevero** [MrChuckomo/poddycast#48]
User can add podcasts only by searching for them in iTunes catalog and subscribing them manually. Option to import OPML files would allow user import all his podcasts with a single click.

**Comment by MrChuckomo** [comment]
It’s also possible to copy a feed-URL into the search field to subscribe to a Podcast. 

It allows you to get Podcasts which are not in iTunes.

**Comment by EthanGrahn** [comment]
I have an initial implementation of this in place, but I wanted to bring up some options on how you (@MrChuckomo) would prefer this implemented. Right now I am using [rss-to-json](https://www.npmjs.com/package/rss-to-json) to check the feed urls in the opml files. While the package is handy for our use case, it doesn't support proxies. rss-to-json uses [axios](https://www.npmjs.com/package/axios) in the backend, which does support proxies. The current callback method of making requests doesn't lend itself well to running the import, but using promises has worked great. So a couple questions: Would you be opposed to using promises? If not, would you want to use axios, or write a version of the existing request function to support promises?
