### ISSUE TITLE
Hosting on a web server?

### ISSUE THREAD

**Issue by onny** [MrChuckomo/poddycast#69]
Hey,
is it possible to host this app on a web server?

Best regards,
Jonas

**Comment by alexdevero** [comment]
The app itself is built into electron app, but electron is basically a webkit-based view. So, it is possible to "replace" electron with standard browser. Then, it can be hosted on a web server as any other website.

**Comment by onny** [comment]
Cool thanks for the replay. But it doesn't sound that easy. If you figured something out or have some tipps, feel free to reopen this issue :)
Thanks,
Jonas
