### ISSUE TITLE
Keep up the good work

### ISSUE THREAD

**Issue by g3blv** [MrChuckomo/poddycast#70]
Sorry couldn't find any other way of reaching out to you. Just have to give some feedback. I've been testing a few podcast players on Ubuntu and so far Poddycast is the one player that works best (for me). Please keep up the good work on Poddycast!

**Comment by alexdevero** [comment]
@g3blv Thanks for reaching out to us. I am glad to hear you like Poddycast. If you have any suggestions feel free to share.
