### ISSUE TITLE
Eliminate podcast settings file

### ISSUE THREAD

**Issue by MrChuckomo** [MrChuckomo/poddycast#74]
Merge `...-podcast_setting.json` into ▶️  `...-favorite_podcasts.json`

The settings file contains just one unique property (`addToInbox`). Which can be included into the favorites file. This should result in less file handling. 

**Related Issues**

- Podcast status refresh (discussion about new property) #73

**Comment by EthanGrahn** [comment]
@MrChuckomo this issue can be closed out. It was resolved by #77. In the future we can remove the [old settings function](https://github.com/MrChuckomo/poddycast/blob/8c1a8b06769ed26b3f7c534306610536d55e3684/app/js/helper/helper_global.js#L294). (currently marked as deprecated)
