### ISSUE TITLE
Add support for RSS audio feeds

### ISSUE THREAD

**Issue by EthanGrahn** [MrChuckomo/poddycast#78]
I found this app while searching for a desktop application to use with a Patreon podcast RSS feed. It would be nice to be able to save RSS feeds the same way as the current itunes podcasts. I have already started implementing this, so I can take on the task. It'll be beneficial if we discuss the implementation here such as new UI to accommodate this, backend implementation, etc.

**Comment by MrChuckomo** [comment]
Sounds like a really nice idea. Honestly I've never thought about it before. And never had a "payed" feed for testing.  
First the focus was fully on supporting Podcasts from iTunes as one of the biggest stores. 

🤔 I guess there're some special things to take care of?! What exactly is the difference between a Patreon feed and one from iTunes?

**Comment by EthanGrahn** [comment]
Much of the backend still interacts the same way. Looking at how your iTunes code works, it seems that the feed is just structured differently and has different naming conventions. I'm doing some research to see if the structure is the same for other RSS feeds, but as of right now it is working correctly with my Patreon feed.

**Comment by MrChuckomo** [comment]
I see. Sounds good so far, if the feed itself is just structured differently a little bit. 

What I'm still concerned about is the privilege of these feeds (like payed feeds). Are there some auth.  tokens etc. required to get access to such a feed? Otherwise you can share it easily with others and they will also have access to these episodes. 

Do we need some extra layer of security here?

**Comment by EthanGrahn** [comment]
For the Patreon feed, every user gets a url with a unique auth token on the end of it. It's possible that there may be other services that require username and password. That will be something else I need to research further.

**Comment by EthanGrahn** [comment]
Here is a snippet of the RSS structure from the Patreon podcast I am using. (unique info redacted)
```
<rss version="2.0"
    xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
    xmlns:atom="http://www.w3.org/2005/Atom"
    xmlns:googleplay="http://www.google.com/schemas/play-podcasts/1.0">
    <channel>
        <title>Title</title>
        <link>link</link>
        <description>description</description>
        <atom:link href="https://www.patreon.com/rss/5429459" rel="self" type="application/rss+xml"></atom:link>
        <itunes:owner>
            <itunes:name>Name</itunes:name>
            <itunes:email>email</itunes:email>
        </itunes:owner>
        <itunes:author>Author</itunes:author>
        <itunes:image href="image link"></itunes:image>
        <googleplay:block>yes</googleplay:block>
        <itunes:block>Yes</itunes:block>
        <language>en-US</language>
        <pubDate>Fri, 13 Nov 2020 02:51:06 GMT</pubDate>
        <lastBuildDate>Fri, 13 Nov 2020 02:51:06 GMT</lastBuildDate>
        <image>
            <url>image url</url>
            <title>podcast title</title>
            <link>patreon link</link>
        </image>
        <item>
            <title>episode title</title>
            <link>patreon post link</link>
            <description>episode description</description>
            <enclosure url="episode url" length="87639109" type="audio/mpeg"></enclosure>
            <guid isPermaLink="false">guid</guid>
            <pubDate>Wed, 11 Nov 2020 08:02:01 GMT</pubDate>
        </item>
```
It has some iTunes specific tags that can be used.

**Comment by EthanGrahn** [comment]
Here is a rough layout of the UI I am using.
![image](https://user-images.githubusercontent.com/14171074/99918415-5545d800-2cdc-11eb-8b5b-0546d75e74be.png)

**Comment by MrChuckomo** [comment]
Looks good! But I'm not sure if an extra UI is needed. Maybe if an extra login is necessary - for username and password input. 

But actually you can use the "Find podcast" input field as well. Basically it searches in iTunes. But it already supports and accepts feed URLs as well. Just past it inside and hit enter. But I never tried Patreon feeds. 

Sorry - forgot to mention it before!

**Comment by EthanGrahn** [comment]
Just gave that a try and it gives an error:
```
Cannot read property 'childNodes' of undefined
```
That is likely due to the different xml structure. I'll dig deeper into that to see if there are modifications I can make to have it support both types of urls.

**Comment by EthanGrahn** [comment]
I have it working now using the existing search bar. The only downside is that the Patreon RSS feed does not provide a value for duration. Working on some touch up now then should be ready to make a pull request.

**Comment by MrChuckomo** [comment]
@EthanGrahn sounds great so far. 

The duration issue might be a little problematic for the playback progress. But should be ok for the search and adding part.

**Comment by EthanGrahn** [comment]
It appears to only be an issue with the list display. Playback duration is still displayed correctly.

![image](https://user-images.githubusercontent.com/14171074/101916330-6a4fb180-3b8c-11eb-9094-3ed5b3829df6.png)
