### ISSUE TITLE
Change size of left side of screen where favorites and whatnot are

### ISSUE THREAD

**Issue by chookity-pokk** [MrChuckomo/poddycast#89]
**Is your feature request related to a problem? Please describe.**
I am using the [Pine Phone](https://www.pine64.org/pinephone/) which is a phone that basically runs Debian and would like to use this but without the side being collapsible it isn't viable unless in landscape mode.

**Describe the solution you'd like**
Left side of the screen and section with play buttons being collapsible

**Describe alternatives you've considered**
Being able to change the size of those areas manually.

**Comment by MrChuckomo** [comment]
Thanks for your feedback @ragreenburg and this nice idea. 
I'll check how I can make the app more mobile friendly. 😃

**Comment by ragreenburg** [comment]
Awesome, I honestly think with just those two changes it would go a long way. I wanted to try to help but all my programming experience is with Python, Fortran, R and SQL so I know nothing about JS or Electron unfortunately.

**Comment by MrChuckomo** [comment]
Hi @ragreenburg, sorry for waiting so long for this feature already. And thank you that you want to take a look. 
So I think you're interested in looking into the layout/ui part of the app.

For this you will only need the `index.html` and the `css` files. I hope this helps. 

## For the left panel you can take a look here: 

https://github.com/MrChuckomo/poddycast/blob/2fddd55aab9f4895a8b5f87f2614db923829c4cd/app/index.html#L35-L101

## For the bottom panel you can take a look here: 

https://github.com/MrChuckomo/poddycast/blob/2fddd55aab9f4895a8b5f87f2614db923829c4cd/app/index.html#L113-L164

## For the CSS you can take a look into these files: 

https://github.com/MrChuckomo/poddycast/blob/2fddd55aab9f4895a8b5f87f2614db923829c4cd/app/index.html#L7-L10

**Comment by ragreenburg** [comment]
No problems! I have been working on a ton of my own projects this last 9 months while working, so I know how hard it can be to get to things like this. Thanks for the info! Do you happen to have build instructions/dependencies? I will hopefully get a bit of time over the weekend to work on this.

**Comment by MrChuckomo** [comment]
This issue is solved and will be available with the next release. 
It relates to issue #104 - they're solved together.
