### ISSUE TITLE
Search doesn't work on Windows

### ISSUE THREAD

**Issue by xmha97** [MrChuckomo/poddycast#95]
Hi, The Poddycast app is great.
but the search doesn't work on Windows
![image](https://user-images.githubusercontent.com/23485114/157392707-4ebbb1b1-d496-4e51-a782-1b329655e1ef.png)
Please fix it.
Thanks.

**Comment by EthanGrahn** [comment]
I'll take a look at this when I get a chance. Are you able to use the previous version for now? https://github.com/MrChuckomo/poddycast/releases/tag/v0.8.0

**Comment by EthanGrahn** [comment]
@xmha97 Would you be able to provide some more information on your setup? This will help me debug faster. What is your windows version and architecture? Which file from the release did you download? (e.g. `Poddycast-win32-x64`)

I am on Windows 10 64 bit and downloaded the latest release using `Poddycast-win32-x64`. Then I searched for "ted" like in your image and didn't get any errors.

**Comment by xmha97** [comment]
I tested again and saw that there was no problem 👌
